<a href="https://colab.research.google.com/github/busubol/Algorithms/blob/master/review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import math
csv = "/content/drive/MyDrive/amazon_dataset.csv"
df = pd.read_csv(csv)
df.head(5)   #show only top 5

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (1,10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42

In [2]:
data = df.copy()  # copy all things from df to data variable
data.describe()   #The describe() method is used for calculating some statistical data like percentile, mean and std of the numerical values of the Series or DataFrame. It analyzes both numeric and object series and also the DataFrame column sets of mixed data types.

,reviews.id,reviews.numHelpful,reviews.rating,reviews.userCity,reviews.userProvince
count,1.0,34131.000000,34627.000000,0.0,0.0
mean,111372787.0,0.630248,4.584573,NaN,NaN
std,NaN,13.215775,0.735653,NaN,NaN
min,111372787.0,0.000000,1.000000,NaN,NaN
25%,111372787.0,0.000000,4.000000,NaN,NaN
50%,111372787.0,0.000000,5.000000,NaN,NaN
75%,111372787.0,0.000000,5.000000,NaN,NaN
max,111372787.0,814.000000,5.000000,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34660 entries, 0 to 34659
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    34660 non-null  object
 1   name                  27900 non-null  object
 2   asins                 34658 non-null  object
 3   brand                 34660 non-null  object
 4   categories            34660 non-null  object
 5   keys                  34660 non-null  object
 6   manufacturer          34660 non-null  object
 7   reviews.date          34621 non-null  object
 8   reviews.dateAdded     24039 non-null  object
 9   reviews.dateSeen      34660 non-null  object
 10  reviews.didPurchase   1 non-null      object
 11  reviews.doRecommend   34066 non-null  object
 12  reviews.id            1 non-null      float64
 13  reviews.numHelpful    34131 non-null  float64
 14  reviews.rating        34627 non-null  float64
 15  reviews.sourceURLs    34660 non-null  object
 16  reviews.text          34659 non-null  object
 17  reviews.title         34655 non-null  object
 18  reviews.userCity      0 non-null      float64
 19  reviews.userProvince  0 non-null      float64
 20  reviews.username      34658 non-null  object
dtypes: float64(5), object(16)
memory usage: 5.6+ MB

In [4]:
print(len(data))  # normally dekhale amn dilei hoy
print("Before {}".format(len(data))) # .format ar vitor na rakle error dekhabe bcz amra akta string hisebe before ar sathe dekhaci
dataAfter = data.dropna(subset=["reviews.rating"]) # removes all NAN in reviews.rating
print("After {}".format(len(dataAfter)))
dataAfter["reviews.rating"] = dataAfter["reviews.rating"].astype(int)

34660
Before 34660
After 34627

<ipython-input-4-ff8eba67dcef>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataAfter["reviews.rating"] = dataAfter["reviews.rating"].astype(int)

In [22]:
dataAfter["reviews.rating"]

0        5
1        5
2        5
3        4
4        5
        ..
34655    3
34656    1
34657    1
34658    1
34659    1
Name: reviews.rating, Length: 34627, dtype: int64

In [6]:
dataAfter

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34655,AVpfiBlyLJeJML43-4Tp,NaN,B006GWO5WK,Amazon,"Computers/Tablets & Networking,Tablet & eBook ...",newamazonkindlefirehd9wpowerfastadaptercharger...,"Amazon Digital Services, Inc",2012-09-18T00:00:00Z,NaN,2015-08-29T00:00:00Z,...,NaN,NaN,NaN,3,http://www.amazon.com/Amazon-PowerFast-Adapter...,This is not appreciably faster than any other ...,Not appreciably faster than any other 1.8A cha...,NaN,NaN,Kris
34656,AVpfiBlyLJeJML43-4Tp,NaN,B006GWO5WK,Amazon,"Computers/Tablets & Networking,Tablet & eBook ...",newamazonkindlefirehd9wpowerfastadaptercharger...,"Amazon Digital Services, Inc",2012-11-21T00:00:00Z,NaN,2015-09-02T00:00:00Z,...,NaN,NaN,NaN,1,http://www.amazon.com/Amazon-PowerFast-Adapter...,Amazon should include this charger with the Ki...,Should be included,NaN,NaN,Jonathan Stewart
34657,AVpfiBlyLJeJML43-4Tp,NaN,B006GWO5WK,Amazon,"Computers/Tablets & Networking,Tablet & eBook ...",newamazonkindlefirehd9wpowerfastadaptercharger...,"Amazon Digital Services, Inc",2012-10-19T00:00:00Z,NaN,2015-09-04T00:00:00Z,...,NaN,NaN,NaN,1,http://www.amazon.com/Amazon-PowerFast-Adapter...,Love my Kindle Fire but I am really disappoint...,Disappointing Charger,NaN,NaN,J Lawson
34658,AVpfiBlyLJeJML43-4Tp,NaN,B006GWO5WK,Amazon,"Computers/Tablets & Networking,Tablet & eBook ...",newamazonkindlefirehd9wpowerfastadaptercharger...,"Amazon Digital Services, Inc",2012-10-31T00:00:00Z,NaN,2015-09-01T00:00:00Z,...,NaN,NaN,NaN,1,http://www.amazon.com/Amazon-PowerFast-Adapter...,I was surprised to find it did not come with a...,Not worth the money,NaN,NaN,Just the Buyer
34659,AVpfiBlyLJeJML43-4Tp,NaN,B006GWO5WK,Amazon,"Computers/Tablets & Networking,Tablet & eBook ...",newamazonkindlefirehd9wpowerfastadaptercharger...,"Amazon Digital Services, Inc",2012-12-23T00:00:00Z,NaN,2015-11-01T00:00:00Z,...,NaN,NaN,NaN,1,http://www.amazon.com/Amazon-PowerFast-Adapter...,to spite the fact that i have nothing but good...,as with everyone else,NaN,NaN,sandi

In [7]:
from sklearn.model_selection import StratifiedShuffleSplit
s = StratifiedShuffleSplit(test_size=0.3)  #akhan e test_size=0.3 mane total data r 30% se test korar jonno rakbe ar baki 70% data diye se machine ke bujhabe je ki holo kmn hoa dorker output 
for train_index, test_index in s.split(dataAfter, dataAfter["reviews.rating"]): #split diye alada kora hoyeche (baki sob info , only rating)
    strat_train = dataAfter.reindex(train_index)
    strat_test = dataAfter.reindex(test_index)

#strat_test

strat_train

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
19693,AV1YnRtnglJLPUi8IJmV,Amazon Kindle Paperwhite - eBook reader - 4 GB...,B00OQVZDJM,Amazon,"Walmart for Business,Office Electronics,Tablet...","amazon/b00oqvzdjm,848719056099,amazonkindlepap...",Amazon,2017-07-07T00:00:00.000Z,2017-09-05T22:09:30Z,"2017-08-31T22:33:03.902Z,2017-08-02T19:54:06.8...",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/9439005/review...,Not that I don't love it but I wish it would h...,Not exactly what I pictured,NaN,NaN,Bear
9959,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-08-09T00:00:00.000Z,2017-05-21T01:49:45Z,"2017-04-30T00:13:00.000Z,2017-06-07T08:17:00.000Z",...,True,NaN,4.0,4.0,http://reviews.bestbuy.com/3545/5025800/review...,I have been wanting to give these little table...,Great value for the money!,NaN,NaN,Jordan
20531,AV1YnRtnglJLPUi8IJmV,"Kindle Voyage E-reader, 6 High-Resolution Disp...",B00OQVZDJM,Amazon,"Walmart for Business,Office Electronics,Tablet...","amazon/b00oqvzdjm,848719056099,amazonkindlepap...",Amazon,2017-01-24T00:00:00.000Z,2017-09-05T22:09:30Z,"2017-08-31T22:32:40.066Z,2017-08-02T22:16:32.5...",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/9439005/review...,"Much easier to read without a heavy book, espe...",Excellent,NaN,NaN,Fuglibug
14254,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2015-12-04T00:00:00.000Z,2017-05-21T04:04:40Z,"2017-04-30T00:26:00.000Z,2017-06-07T08:10:00.000Z",...,True,NaN,1.0,5.0,http://reviews.bestbuy.com/3545/5025800/review...,I haven't found anything I don't like about th...,The Fire 7 is awesome!,NaN,NaN,Velma
9834,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-08-19T00:00:00.000Z,2017-05-21T01:48:38Z,"2017-04-30T00:13:00.000Z,2017-06-07T08:16:00.000Z",...,True,NaN,1.0,5.0,http://reviews.bestbuy.com/3545/5025800/review...,Good tablet. A lot to do. Good storage. Would ...,Great,NaN,NaN,Harper747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17156,AVqVGWLKnnc1JgDc3jF1,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",B018Y23MNM,Amazon,"Tablets,Fire Tablets,Computers & Tablets,All T...",firekidseditiontablet7displaywifi16gbgreenkidp...,Amazon,2017-02-19T00:00:00.000Z,2017-06-21T07:38:36Z,"2017-06-04T02:18:01.504Z,2017-06-03T18:42:11.710Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5026300/review...,Grandson loves his new tablet. Had to set him ...,great for my grandson,NaN,NaN,grandpa
7042,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-11-21T00:00:00.000Z,2017-05-21T01:20:33Z,"2017-04-30T00:08:00.000Z,2017-06-07T08:16:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5025800/review...,Cheap tablet for someone that knows little abo...,mother day present,NaN,NaN,Roxxitas
6419,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-04-20T00:00:00.000Z,2017-05-21T01:18:08Z,"2017-04-30T00:08:00.000Z,2017-06-07T08:18:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5025800/review...,I bought one of these for my father. He loves ...,Well built!,NaN,NaN,YourFriendlyConsumer
19256,AV1YnRtnglJLPUi8IJmV,Amazon Kindle Paperwhite - eBook reader - 4 GB...,B00OQVZDJM,Amazon,"Walmart for Business,Office Electronics,Tablet...","amazon/b00oqvzdjm,848719056099,amazonkindlepap...",Amazon,2017-03-26T00:00:00.000Z,2017-09-05T22:09:30Z,"2017-08-31T22:33:16.568Z,2017-08-02T19:54:26.6...",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/9439005/review...,The Kindle is like carrying a library in your ...,Great thing for readers,NaN,NaN,RussR
3783,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-06-24T00:00:00.000Z,2017-07-02T17:06:48Z,"2017-06-07T08:18:00.000Z,2017-04-30T00:20:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5025800/review...,"Great for music ,movies and games a lot of spa...",Great size,NaN,NaN,Renee123

In [8]:
len(strat_train)  #total number of training data.

24238

In [23]:
strat_train["reviews.rating"].value_counts()/len(strat_train) # value_count() counts all the values based on column

5.0    0.685989
4.0    0.247421
3.0    0.043114
2.0    0.011635
1.0    0.010933
Name: reviews.rating, dtype: float64

In [24]:
len(strat_test)

10389

In [25]:
strat_test["reviews.rating"].value_counts()/len(strat_test)

5.0    0.686399
4.0    0.244586
3.0    0.043508
1.0    0.012995
2.0    0.011454
Name: reviews.rating, dtype: float64

In [26]:
reviews = strat_train.copy()
reviews.head(2)

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,Sentiment
19693,AV1YnRtnglJLPUi8IJmV,Amazon Kindle Paperwhite - eBook reader - 4 GB...,B00OQVZDJM,Amazon,"Walmart for Business,Office Electronics,Tablet...","amazon/b00oqvzdjm,848719056099,amazonkindlepap...",Amazon,2017-07-07T00:00:00.000Z,2017-09-05T22:09:30Z,"2017-08-31T22:33:03.902Z,2017-08-02T19:54:06.8...",...,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/9439005/review...,Not that I don't love it but I wish it would h...,Not exactly what I pictured,NaN,NaN,Bear,Positive
9959,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-08-09T00:00:00.000Z,2017-05-21T01:49:45Z,"2017-04-30T00:13:00.000Z,2017-06-07T08:17:00.000Z",...,NaN,4.0,4.0,http://reviews.bestbuy.com/3545/5025800/review...,I have been wanting to give these little table...,Great value for the money!,NaN,NaN,Jordan,Positive

In [27]:
def sentiments(rating):
    
    if (rating == 5) or (rating == 4):
        return "Positive"
        
    elif rating == 3:
        return "Neutral"

    elif (rating == 2) or (rating == 1):
        return "Negative"
# Add sentiments to the data
strat_train["Sentiment"] = strat_train["reviews.rating"].apply(sentiments)
strat_test["Sentiment"] = strat_test["reviews.rating"].apply(sentiments)
strat_train["Sentiment"][:50]
#strat_test["Sentiment"][:50]

19693    Positive
9959     Positive
20531    Positive
14254    Positive
9834     Positive
20906    Positive
15827    Positive
29785     Neutral
17195    Positive
5022     Positive
9184     Positive
2499     Positive
833      Positive
20556    Positive
8955     Positive
18589    Positive
8548     Positive
28512    Positive
21636    Positive
29507    Positive
11060    Positive
17722    Positive
21985    Positive
8202     Positive
12795    Positive
19973    Positive
1429     Positive
28459    Positive
30736    Positive
2268     Positive
31863    Positive
4433     Positive
33572    Positive
30570    Positive
31665    Positive
8176     Positive
20481    Positive
16009    Negative
22441    Positive
20138    Positive
2531      Neutral
8604     Positive
17999    Positive
23544    Positive
23286    Positive
23496    Positive
31701    Positive
18671    Positive
14683    Positive
15511    Positive
Name: Sentiment, dtype: object

In [29]:
strat_train["Sentiment"].value_counts()*100/len(strat_train) # je data train korlam tar koto percent positive,negative,neutral ta dekhano holo

Positive    93.341035
Neutral      4.311412
Negative     2.256787
Name: Sentiment, dtype: float64

In [30]:
strat_test["Sentiment"].value_counts()*100/len(strat_test) # je data diye test korlam tar koto percent positive,negative,neutral ta dekhano holo

Positive    93.098470
Neutral      4.350756
Negative     2.444894
Name: Sentiment, dtype: float64

In [31]:
strat_test.head(5) #amra akhan e new akta column sentiment dekte pabo ja kina .apply() use kore rekhecilam sentiment column ar modhe

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,Sentiment
15602,AVpjEN4jLJeJML43rpUe,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",B018Y225IA,Amazon,"Computers/Tablets & Networking,Tablets & eBook...","841667103143,0841667103143,brandnewamazonkindl...",Amazon,2016-07-01T00:00:00.000Z,NaN,"2017-08-27T00:00:00Z,2017-08-09T00:00:00Z,2017...",...,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5025500/review...,"This was a great tablet, but I downgraded to t...",didn't keep long but downgraded,NaN,NaN,CharleSub,Positive
1418,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2016-12-30T00:00:00.000Z,2017-05-21T05:59:53Z,"2017-04-30T00:43:00.000Z,2017-06-07T09:03:00.000Z",...,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,We purchased this tablet for our son for Chris...,Nice tablet,NaN,NaN,Rick,Positive
17820,AV1YnRtnglJLPUi8IJmV,Amazon Kindle Paperwhite - eBook reader - 4 GB...,B00OQVZDJM,Amazon,"Walmart for Business,Office Electronics,Tablet...","amazon/b00oqvzdjm,848719056099,amazonkindlepap...",Amazon,2015-10-19T00:00:00.000Z,2017-09-05T22:09:30Z,"2017-08-31T22:34:06.394Z,2017-08-02T19:49:52.9...",...,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/9439005/review...,The Kindle Paper White is the perfect gift for...,Easy to Use,NaN,NaN,Tara,Positive
3877,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2017-01-01T00:00:00.000Z,2017-07-02T16:09:46Z,"2017-06-07T08:16:00.000Z,2017-04-30T00:12:00.000Z",...,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5025800/review...,It's the best price media streaming tablet on ...,Unbeatable for the price!,NaN,NaN,MadBenco,Positive
11165,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-01-14T00:00:00.000Z,2017-05-21T02:31:53Z,"2017-04-30T00:18:00.000Z,2017-06-07T08:13:00.000Z",...,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5025800/review...,There is also a way to add the play store .......,good for most common apps,NaN,NaN,Damian,Positive

In [17]:
X_train = strat_train["reviews.text"] # review je column e ache tar name "reviews.text" tai column nam ota dilam
X_train_targetSentiment = strat_train["Sentiment"]  # sentiment nam e je new column create holo seta ke call korlam
X_test = strat_test["reviews.text"]
X_test_targetSentiment = strat_test["Sentiment"]
#X_train
#X_train_targetSentiment
print(len(X_train), len(X_test))

24238 10389

In [32]:
X_train.isnull().count

<bound method Series.count of 19693    False
9959     False
20531    False
14254    False
9834     False
         ...
17156    False
7042     False
6419     False
19256    False
3783     False
Name: reviews.text, Length: 24238, dtype: bool>

In [33]:
# Replace "nan" with space

X_train = X_train.fillna(' ')
X_test = X_test.fillna(' ')

X_train_targetSentiment = X_train_targetSentiment.fillna(' ')
X_test_targetSentiment = X_test_targetSentiment.fillna(' ')

# Text processing and counting
from sklearn.feature_extraction.text import CountVectorizer 
count_vect = CountVectorizer()

X_train_counts = count_vect.fit_transform(X_train) 
#count_vect.get_feature_names_out()
#print(X_train_counts.toarray())
print(X_train_counts)
X_train_counts.shape   #Here we have 24238 training samples and 11891 distinct words in our training sample.

  (0, 7098)	1
  (0, 10489)	1
  (0, 3263)	1
  (0, 6322)	1
  (0, 5700)	2
  (0, 1770)	1
  (0, 11596)	1
  (0, 11685)	1
  (0, 4938)	1
  (0, 1344)	1
  (0, 6221)	1
  (0, 1426)	1
  (0, 6797)	1
  (0, 1551)	1
  (0, 6162)	1
  (1, 7098)	4
  (1, 10489)	6
  (1, 5700)	9
  (1, 1770)	6
  (1, 4938)	3
  (1, 1344)	1
  (1, 6221)	1
  (1, 11378)	1
  (1, 10665)	15
  (1, 4597)	1
  :	:
  (24235, 8658)	1
  (24235, 10454)	1
  (24236, 5700)	2
  (24236, 6162)	1
  (24236, 10498)	1
  (24236, 5684)	2
  (24236, 5361)	1
  (24236, 11778)	1
  (24236, 5905)	1
  (24236, 6109)	1
  (24236, 3981)	1
  (24236, 1895)	1
  (24236, 1897)	1
  (24236, 3753)	1
  (24236, 1215)	1
  (24237, 4286)	1
  (24237, 802)	1
  (24237, 4762)	1
  (24237, 7197)	1
  (24237, 6831)	1
  (24237, 6309)	1
  (24237, 4498)	1
  (24237, 6876)	1
  (24237, 9759)	1
  (24237, 5380)	1

(24238, 11817)

In [34]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(use_idf=False)
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
print(X_train_tfidf)

  (0, 1344)	0.23570226039551587
  (0, 1426)	0.23570226039551587
  (0, 1551)	0.23570226039551587
  (0, 1770)	0.23570226039551587
  (0, 3263)	0.23570226039551587
  (0, 4938)	0.23570226039551587
  (0, 5700)	0.47140452079103173
  (0, 6162)	0.23570226039551587
  (0, 6221)	0.23570226039551587
  (0, 6322)	0.23570226039551587
  (0, 6797)	0.23570226039551587
  (0, 7098)	0.23570226039551587
  (0, 10489)	0.23570226039551587
  (0, 11596)	0.23570226039551587
  (0, 11685)	0.23570226039551587
  (1, 400)	0.04929638584471639
  (1, 426)	0.04929638584471639
  (1, 633)	0.024648192922358196
  (1, 730)	0.024648192922358196
  (1, 749)	0.024648192922358196
  (1, 767)	0.14788915753414916
  (1, 798)	0.07394457876707458
  (1, 802)	0.09859277168943278
  (1, 848)	0.024648192922358196
  (1, 878)	0.024648192922358196
  :	:
  (24235, 11523)	0.07881104062391006
  (24235, 11569)	0.07881104062391006
  (24236, 1215)	0.22941573387056174
  (24236, 1895)	0.22941573387056174
  (24236, 1897)	0.22941573387056174
  (24236, 3753)	0.22941573387056174
  (24236, 3981)	0.22941573387056174
  (24236, 5361)	0.22941573387056174
  (24236, 5684)	0.4588314677411235
  (24236, 5700)	0.4588314677411235
  (24236, 5905)	0.22941573387056174
  (24236, 6109)	0.22941573387056174
  (24236, 6162)	0.22941573387056174
  (24236, 10498)	0.22941573387056174
  (24236, 11778)	0.22941573387056174
  (24237, 802)	0.31622776601683794
  (24237, 4286)	0.31622776601683794
  (24237, 4498)	0.31622776601683794
  (24237, 4762)	0.31622776601683794
  (24237, 5380)	0.31622776601683794
  (24237, 6309)	0.31622776601683794
  (24237, 6831)	0.31622776601683794
  (24237, 6876)	0.31622776601683794
  (24237, 7197)	0.31622776601683794
  (24237, 9759)	0.31622776601683794